name: 'Build debian package cuttlefish-cvdremote'
inputs:
  version:
    required: false
runs:
  using: "composite"
  steps:
  - name: Install dependencies
    uses: actions/setup-go@v3
    with:
      go-version: 1.23.4
  - name: setup apt
    run: apt update -y && apt upgrade -y
    shell: bash
  - name: install debuild dependencies
    run: apt install -y config-package-dev debhelper-compat devscripts git golang
    shell: bash
  - name: Modify version format
    if: inputs.version != ''
    run: |
      sed -i "1s/(\([0-9]\+.[0-9]\+.[0-9]\+\))/(${{ inputs.version }})/g" \
        build/debian/cuttlefish_cvdremote/debian/changelog
    shell: bash
  - name: Build package
    run: |
      pushd build/debian/cuttlefish_cvdremote
      dpkg-buildpackage -i -uc -us -b
      popd
      mv build/debian/cuttlefish-cvdremote_*.deb .
    shell: bash
  - name: Install package
    run: dpkg -i cuttlefish-cvdremote_*.deb || apt install -y
    shell: bash
