name: 'Build debian package cuttlefish-cvdremote'
runs:
  using: "composite"
  steps:
  - name: Install dependencies
    uses: actions/setup-go@v3
    with:
      go-version: 1.23.4
  - name: setup apt
    run: apt update -y && apt upgrade -y
    shell: bash
  - name: install debuild dependencies
    run: apt install -y config-package-dev debhelper-compat devscripts git golang
    shell: bash
  - name: Setup nightly version
    run: |
      # TODO(b/440196950): Setup condition on this step when we build
      # stable/unstable versions here too.

      # Modify debian/changelog to build debian package with desired version
      # format.
      # Stable/Unstable version format : X.Y.Z
      # Nightly version format         : X.Y.Z~gitYYYYMMDD.<Github SHA 8 digit>
      DATE=$(date -u +'%Y%m%d')
      SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
      SUFFIX="~git${DATE}.${SHORT_SHA}"
      sed -i "1s/(\([0-9]\+.[0-9]\+.[0-9]\+\))/(\1${SUFFIX})/g" \
        build/debian/cuttlefish_cvdremote/debian/changelog
    shell: bash
  - name: Build package
    run: |
      pushd build/debian/cuttlefish_cvdremote
      dpkg-buildpackage -i -uc -us -b
      popd
      mv build/debian/cuttlefish-cvdremote_*.deb .
    shell: bash
  - name: Install package
    run: dpkg -i cuttlefish-cvdremote_*.deb || apt install -y
    shell: bash
