name: 'Build debian package cuttlefish-cvdremote'
inputs:
  arch:
    required: true
runs:
  using: "composite"
  steps:
  - name: Install dependencies
    uses: actions/setup-go@v3
    with:
      go-version: 1.23.4
  - name: setup apt
    run: apt update -y && apt upgrade -y
    shell: bash
  - name: install debuild dependencies
    run: apt install -y config-package-dev debhelper-compat devscripts git golang
    shell: bash
  - name: Build package
    run: cd build/debian/cuttlefish_cvdremote && dpkg-buildpackage -i -uc -us -b
    shell: bash
  - name: Install package
    run: dpkg -i build/debian/cuttlefish-cvdremote_*.deb || apt install -y
    shell: bash
  - name: Upload debian package
    uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # aka v4.0.0
    with:
      name: cuttlefish-cvdremote-${{ inputs.arch }}
      path: build/debian/cuttlefish-cvdremote_*.deb
