name: 'Deploy docker image cuttlefish-cloud-orchestrator'
inputs:
  arch:
    required: true
  version:
    required: true
runs:
  using: "composite"
  steps:
  - name: Deploy docker image into Artifact Registry
    run: |
      TAG=${{ inputs.version }}-${{ inputs.arch }}
      REMOTE_IMAGE_TAG=us-docker.pkg.dev/android-cuttlefish-artifacts/cuttlefish-orchestration/cuttlefish-cloud-orchestrator:${TAG}

      docker tag cuttlefish-cloud-orchestrator ${REMOTE_IMAGE_TAG}
      docker push ${REMOTE_IMAGE_TAG}
    shell: bash
