name: 'Deploy debian package cuttlefish-cvdremote'
inputs:
  path:
    required: true
runs:
  using: "composite"
  steps:
  - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v3.0.0'
    with:
      version: '>= 363.0.0'
  - name: Deploy deb package into Artifact Registry
    run: |
      gcloud --project=android-cuttlefish-artifacts \
        artifacts apt upload \
        android-cuttlefish-nightly \
        --location=us \
        --source=${{ inputs.path }}
    shell: bash
