name: 'Deploy debian package cuttlefish-cvdremote'
inputs:
  deploy-channel:
    required: true
  path:
    required: true
runs:
  using: "composite"
  steps:
  - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v3.0.0'
    with:
      version: '>= 363.0.0'
  - name: Deploy deb package into Artifact Registry
    run: |
      if [[ ${{ inputs.deploy-channel }} == "stable" ]]; then
        REPO=android-cuttlefish
      else
        REPO=android-cuttlefish-${{ inputs.deploy-channel }}
      fi

      gcloud --project=android-cuttlefish-artifacts \
        artifacts apt upload \
        ${REPO} \
        --location=us \
        --source=${{ inputs.path }}
    shell: bash
