name: Build and test

on: [pull_request, push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Install dependencies
      uses: actions/setup-go@v3
      with:
        go-version: '1.16.0'
    - run: go version
    - name: Build
      run: go build ./...
    - name: Test
      run: go test ./...
