name: cvdremote Linux 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: cvdremote-build-linux
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Go 
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.0'
      - run: go version
      - name: Build
        run: cd cmd/cvdremote && go build .
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: cvdremote 
          path: cmd/cvdremote/cvdremote 
