name: Unstable channel

on:
  push:
    branches:
      - 'version-[0-9]+.[0-9]+-dev'

jobs:
  deploy:
    if: github.repository_owner == 'google'
    uses: ./.github/workflows/deployment.yaml
    with:
      deploy-channel: unstable
    secrets:
      artifact-registry-uploader-json-creds: ${{ secrets.ARTIFACT_REGISTRY_UPLOADER }}
